- hosts: mongod-1
  become: yes
  become_user: root
  tasks:
  - name:  comment replication 
    replace:
      path: /etc/mongod.conf
      backup: yes
      regexp: '^(.*replication.*)'
      replace: '#\1'
  - name:  delete line replSetName 
    lineinfile: 
      dest: /etc/mongod.conf
      state: absent 
      regexp: '(.*replSetName.*)'
  # - name:  comment replSetName 
  #   replace:
  #     path: /etc/mongod.conf
  #     backup: yes
  #     regexp: '(.*replSetName.*)'
  #     replace: '#\1'
  - name: restart mongod
    service: name=mongod state=restarted  