- hosts: local
  tasks:
  - name: Ensure replicaset rs0 exists
    community.mongodb.mongodb_replicaset:
      login_host: localhost
      login_port: 3001
      login_user: admin
      login_password: secret
      login_database: admin
      replica_set: rs0
      members: localhost:3001
      validate: no